COMPOSITION_NAME = "1k-attack-cold-boot-covert-flash"

# time to run simulation (after warmup) (>2 epochs)
T_RUN = "18m"

# total number of nodes in simulation
N_NODES = 1250

# number of nodes that are attackers
N_ATTACK_NODES = 250

N_ATTACK_PEERS_PER_NODE = 16

ATTACK_DEGREE = 20

ATTACK_SINGLE_NODE = false

ATTACKER_CONNECT_DELAYS = "4000@0s"

HONEST_CONNECT_DELAYS = "1000@1s"

T_SYBIL_ATTACK_DELAY = "5m"

T_SETUP = "5m"

OPPORTUNISTIC_GRAFT_TICKS = 10

OPPORTUNISTIC_GRAFT_THRESHOLD = 5
