COMPOSITION_NAME = "1k-attack-cold-boot-oppgraft"
# total number of nodes in simulation
N_NODES = 1250

# number of nodes that are attackers
N_ATTACK_NODES = 250

N_ATTACK_PEERS_PER_NODE = 16

# type of attack node
ATTACK_NODE_TYPE = "sybil"

ATTACK_DEGREE = 20

ATTACK_SINGLE_NODE = false

ATTACKER_CONNECT_DELAYS = "4000@0s"

OPPORTUNISTIC_GRAFT_TICKS = 10

OPPORTUNISTIC_GRAFT_THRESHOLD = 5
