COMPOSITION_NAME = "1k-attack-eclipse-net"
# total number of nodes in simulation
N_NODES = 1250

# number of nodes that are attackers
N_ATTACK_NODES = 250

N_ATTACK_PEERS_PER_NODE = 16

# type of attack node
ATTACK_NODE_TYPE = "sybil"

ATTACK_DEGREE = 100

ATTACK_SINGLE_NODE = false

ATTACKER_CONNECT_DELAYS = "4000@1m"
