COMPOSITION_NAME = "1k-attack-eclipse-single"

# total number of nodes in simulation
N_NODES = 1250

# number of nodes that are attackers
N_ATTACK_NODES = 250

N_ATTACK_PEERS_PER_NODE = 4

# type of attack node
ATTACK_NODE_TYPE = "sybil"

ATTACK_DEGREE = 1

ATTACK_SINGLE_NODE = true

ATTACKER_CONNECT_DELAYS = "1000@1m"
