COMPOSITION_NAME = "1k-attack-colocation"
# total number of nodes in simulation
N_NODES = 1025

# number of nodes that are attackers
N_ATTACK_NODES = 25

N_ATTACK_PEERS_PER_NODE = 160

# type of attack node
ATTACK_NODE_TYPE = "sybil"

ATTACK_DEGREE = 20

ATTACK_SINGLE_NODE = false

ATTACKER_CONNECT_DELAYS = "4000@0s"

[PEER_SCORE_PARAMS]

IPColocationFactorWeight=-10
